# Generated by Django 4.1.1 on 2022-09-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomeBG name')),
            ],
        ),
        migrations.CreateModel(
            name='HomeIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='HomeIntro title')),
                ('name', models.CharField(max_length=30, verbose_name='HomeIntro name')),
                ('about', models.TextField(verbose_name='HomeIntro about')),
            ],
            options={
                'verbose_name': 'HomeIntro',
                'verbose_name_plural': 'HomeIntros',
            },
        ),
    ]
