# Generated by Django 4.1.1 on 2022-09-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homeservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeService1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='HomeService1 name')),
                ('name1', models.CharField(max_length=30, verbose_name='HomeService1 name1')),
                ('name2', models.CharField(max_length=30, verbose_name='HomeService1 name2')),
                ('name3', models.CharField(max_length=30, verbose_name='HomeService1 name3')),
                ('name4', models.CharField(max_length=30, verbose_name='HomeService1 name4')),
                ('name5', models.CharField(max_length=30, verbose_name='HomeService1 name5')),
                ('about', models.TextField(verbose_name='HomeService1 about')),
            ],
            options={
                'verbose_name': 'HomeService1',
                'verbose_name_plural': 'HomeService1s',
            },
        ),
    ]
