# Generated by Django 4.1.1 on 2022-09-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_homeserv_delete_homeservice1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeServ',
        ),
    ]
