# Generated by Django 4.1.1 on 2022-09-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_homeserv_delete_homeservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeServ1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='HomeServ1 name')),
                ('name1', models.CharField(max_length=30, verbose_name='HomeServ1 name1')),
                ('name2', models.CharField(max_length=30, verbose_name='HomeServ1 name2')),
                ('name3', models.CharField(max_length=30, verbose_name='HomeServ1 name3')),
                ('name4', models.CharField(max_length=30, verbose_name='HomeServ1 name4')),
                ('name5', models.CharField(max_length=30, verbose_name='HomeServ1 name5')),
                ('about', models.TextField(verbose_name='HomeServ1 about')),
            ],
            options={
                'verbose_name': 'HomeServ1',
                'verbose_name_plural': 'HomeServ1s',
            },
        ),
        migrations.CreateModel(
            name='HomeServ2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='HomeServ2 name')),
                ('about', models.TextField(verbose_name='HomeServ2 about')),
            ],
            options={
                'verbose_name': 'HomeServ2',
                'verbose_name_plural': 'HomeServ2s',
            },
        ),
        migrations.CreateModel(
            name='HomeServ3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='HomeServ3 name')),
                ('about', models.TextField(verbose_name='HomeServ3 about')),
            ],
            options={
                'verbose_name': 'HomeServ3',
                'verbose_name_plural': 'HomeServ3s',
            },
        ),
        migrations.DeleteModel(
            name='HomeServ',
        ),
    ]
