# Generated by Django 4.1.1 on 2022-09-10 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_homeserv1_homeserv2_homeserv3_delete_homeserv'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='About slug')),
                ('img', models.ImageField(upload_to='media', verbose_name='About img')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Home name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Home img')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Home slug')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Homes',
            },
        ),
        migrations.DeleteModel(
            name='HomeImg',
        ),
        migrations.AddField(
            model_name='about',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeabout', to='main.home'),
        ),
    ]
