# Generated by Django 4.1.1 on 2022-09-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='name',
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
